/** Player de música: uma única instância de HTMLAudioElement. */
(function(){
"use strict";
const tracks=(window.siteContent&&Array.isArray(window.siteContent.musicas)?window.siteContent.musicas:[]).filter(t=>t&&t.arquivo);
if(!tracks.length)return;
const root=document.createElement("div");
root.className="music-player";
root.innerHTML=`<div class="music-player__mini"><button class="music-player__mini-main" type="button" data-open aria-label="Abrir player de músicas" aria-expanded="false"><span class="music-player__mini-cover music-player__cover" data-mini-cover aria-hidden="true"></span><span class="music-player__mini-info"><strong data-mini-title></strong><span data-mini-artist></span></span></button><span class="music-player__mini-actions"><button class="music-player__mini-play" type="button" data-play aria-label="Reproduzir" aria-pressed="false">▶</button><span class="music-player__heart" aria-hidden="true">♥</span><span class="music-player__open" aria-hidden="true">↑</span></span></div><div class="music-player__backdrop" data-close hidden></div><section class="music-player__sheet" data-sheet role="dialog" aria-modal="true" aria-label="Player de músicas" aria-hidden="true"><div class="music-player__sheet-inner"><button class="music-player__close" type="button" data-close aria-label="Fechar player de músicas">↓</button><div class="music-player__decor" aria-hidden="true"><span>♥</span><span>♥</span><span>♥</span></div><div class="music-player__now"><div class="music-player__large-cover music-player__cover" data-cover aria-hidden="true"></div><div class="music-player__meta"><p class="music-player__eyebrow">TOCANDO AGORA</p><h2 data-title></h2><p data-artist></p></div></div><div class="music-player__progress"><input data-progress type="range" min="0" max="0" value="0" step=".1" aria-label="Progresso da música"><div class="music-player__times"><span data-current>0:00</span><span data-duration>0:00</span></div></div><div class="music-player__controls"><button class="music-player__control" type="button" data-prev aria-label="Música anterior">⏮</button><button class="music-player__control music-player__control--primary" type="button" data-main-play aria-label="Reproduzir" aria-pressed="false">▶</button><button class="music-player__control" type="button" data-next aria-label="Próxima música">⏭</button></div><div class="music-player__volume"><span aria-hidden="true">🔈</span><input data-volume type="range" min="0" max="1" value="1" step=".01" aria-label="Volume"><span aria-hidden="true">🔊</span></div><div class="music-player__playlist"><div class="music-player__playlist-heading"><p class="music-player__eyebrow">PLAYLIST</p><span data-count></span></div><div class="music-player__tracks" data-tracks></div></div></div></section><audio data-audio preload="metadata"></audio>`;
document.body.appendChild(root);
const q=s=>root.querySelector(s),audio=q("[data-audio]"),mini=q(".music-player__mini"),openButton=q("[data-open]"),sheet=q("[data-sheet]"),backdrop=q("[data-close]"),miniCover=q("[data-mini-cover]"),cover=q("[data-cover]"),miniTitle=q("[data-mini-title]"),miniArtist=q("[data-mini-artist]"),title=q("[data-title]"),artist=q("[data-artist]"),progress=q("[data-progress]"),current=q("[data-current]"),duration=q("[data-duration]"),volume=q("[data-volume]"),miniPlay=q("[data-play]"),mainPlay=q("[data-main-play]"),prev=q("[data-prev]"),next=q("[data-next]"),trackList=q("[data-tracks]"),count=q("[data-count]");
let index=0,lastFocus=null;
const time=v=>Number.isFinite(v)&&v>=0?Math.floor(v/60)+":"+String(Math.floor(v%60)).padStart(2,"0"):"0:00";
function setCover(el,t){el.replaceChildren();el.classList.remove("music-player__cover--placeholder");if(!t.capa){el.classList.add("music-player__cover--placeholder");el.textContent="♥";return}const img=document.createElement("img");img.src=t.capa;img.alt=t.altCapa||("Capa de "+t.titulo);img.loading="lazy";img.decoding="async";img.onerror=()=>{el.replaceChildren();el.classList.add("music-player__cover--placeholder");el.textContent="♥"};el.appendChild(img)}
function render(){trackList.replaceChildren();tracks.forEach((t,i)=>{const b=document.createElement("button");b.type="button";b.className="music-player__track";b.setAttribute("aria-current",String(i===index));b.setAttribute("aria-label","Tocar "+t.titulo);const n=document.createElement("span");n.className="music-player__track-number";n.textContent=String(i+1).padStart(2,"0");const c=document.createElement("span");c.className="music-player__track-cover music-player__cover";setCover(c,t);const info=document.createElement("span");info.className="music-player__track-info";const tt=document.createElement("strong");tt.textContent=t.titulo;const aa=document.createElement("span");aa.textContent=t.artista;info.append(tt,aa);const s=document.createElement("span");s.className="music-player__track-state";s.textContent=i===index&&!audio.paused?"♫":"";b.append(n,c,info,s);b.addEventListener("click",()=>load(i,true));trackList.appendChild(b)});count.textContent=tracks.length+" faixas"}
function state(){const playing=!audio.paused&&!audio.ended;[miniPlay,mainPlay].forEach(b=>{b.textContent=playing?"❚❚":"▶";b.setAttribute("aria-label",playing?"Pausar":"Reproduzir");b.setAttribute("aria-pressed",String(playing))});mini.classList.toggle("is-playing",playing);openButton.setAttribute("aria-expanded",String(!sheet.hidden&&sheet.classList.contains("is-open")));root.querySelectorAll(".music-player__track").forEach((b,i)=>{b.setAttribute("aria-current",String(i===index));const s=b.querySelector(".music-player__track-state");if(s)s.textContent=i===index&&playing?"♫":""})}
function update(){progress.max=Number.isFinite(audio.duration)?audio.duration:0;progress.value=Number.isFinite(audio.currentTime)?audio.currentTime:0;current.textContent=time(audio.currentTime);duration.textContent=time(audio.duration)}
function load(i,autoplay){index=Math.max(0,Math.min(i,tracks.length-1));const t=tracks[index];audio.pause();audio.src=t.arquivo;audio.load();[miniCover,cover].forEach(el=>setCover(el,t));miniTitle.textContent=t.titulo;miniArtist.textContent=t.artista;title.textContent=t.titulo;artist.textContent=t.artista;update();state();render();if(autoplay){const p=audio.play();if(p&&p.catch)p.catch(state)}}
function step(d){const target=index+d;if(target>=0&&target<tracks.length)load(target,true)}
function open(){lastFocus=document.activeElement;sheet.hidden=false;backdrop.hidden=false;requestAnimationFrame(()=>{sheet.classList.add("is-open");sheet.setAttribute("aria-hidden","false");openButton.setAttribute("aria-expanded","true")});q(".music-player__close").focus()}
function close(){sheet.classList.remove("is-open");sheet.setAttribute("aria-hidden","true");openButton.setAttribute("aria-expanded","false");setTimeout(()=>{if(!sheet.classList.contains("is-open")){sheet.hidden=true;backdrop.hidden=true}},240);if(lastFocus&&lastFocus.focus)lastFocus.focus()}
openButton.addEventListener("click",open);miniPlay.addEventListener("click",e=>{e.stopPropagation();audio.paused?audio.play().catch(state):audio.pause()});mainPlay.addEventListener("click",()=>audio.paused?audio.play().catch(state):audio.pause());prev.addEventListener("click",()=>step(-1));next.addEventListener("click",()=>step(1));progress.addEventListener("input",()=>audio.currentTime=Number(progress.value));volume.addEventListener("input",()=>audio.volume=Number(volume.value));root.querySelectorAll("[data-close]").forEach(el=>el.addEventListener("click",close));audio.addEventListener("loadedmetadata",update);audio.addEventListener("timeupdate",update);audio.addEventListener("play",state);audio.addEventListener("pause",state);audio.addEventListener("ended",()=>index<tracks.length-1?load(index+1,true):state());audio.addEventListener("error",()=>{state();duration.textContent="Indisponível"});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!sheet.hidden)close()});
window.musicPlayer={ready:true,source:audio,play:()=>audio.play(),pause:()=>{audio.pause();return true},open,close,next:()=>step(1),previous:()=>step(-1)};
load(0,false);
})();